// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: gt06_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendGt06CmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`                   //设备号
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`              //指令内容
	TimeId   uint64 `protobuf:"varint,4,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *SendGt06CmdRequest) Reset() {
	*x = SendGt06CmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gt06_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGt06CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGt06CmdRequest) ProtoMessage() {}

func (x *SendGt06CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gt06_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGt06CmdRequest.ProtoReflect.Descriptor instead.
func (*SendGt06CmdRequest) Descriptor() ([]byte, []int) {
	return file_gt06_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendGt06CmdRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SendGt06CmdRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SendGt06CmdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGt06CmdRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

type Gt06CommonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Gt06CommonReply) Reset() {
	*x = Gt06CommonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gt06_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gt06CommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gt06CommonReply) ProtoMessage() {}

func (x *Gt06CommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_gt06_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gt06CommonReply.ProtoReflect.Descriptor instead.
func (*Gt06CommonReply) Descriptor() ([]byte, []int) {
	return file_gt06_service_proto_rawDescGZIP(), []int{1}
}

func (x *Gt06CommonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gt06_service_proto protoreflect.FileDescriptor

var file_gt06_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x74, 0x30, 0x36, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x77, 0x0a,
	0x12, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x74, 0x30, 0x36, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69,
	0x6d, 0x65, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x74, 0x30, 0x36, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x4f, 0x0a, 0x0b, 0x47, 0x74, 0x30, 0x36, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x1b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x74, 0x30, 0x36,
	0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x74, 0x30, 0x36, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gt06_service_proto_rawDescOnce sync.Once
	file_gt06_service_proto_rawDescData = file_gt06_service_proto_rawDesc
)

func file_gt06_service_proto_rawDescGZIP() []byte {
	file_gt06_service_proto_rawDescOnce.Do(func() {
		file_gt06_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gt06_service_proto_rawDescData)
	})
	return file_gt06_service_proto_rawDescData
}

var file_gt06_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gt06_service_proto_goTypes = []interface{}{
	(*SendGt06CmdRequest)(nil), // 0: service.SendGt06CmdRequest
	(*Gt06CommonReply)(nil),    // 1: service.Gt06CommonReply
}
var file_gt06_service_proto_depIdxs = []int32{
	0, // 0: service.Gt06Service.SendCmd:input_type -> service.SendGt06CmdRequest
	1, // 1: service.Gt06Service.SendCmd:output_type -> service.Gt06CommonReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gt06_service_proto_init() }
func file_gt06_service_proto_init() {
	if File_gt06_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gt06_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGt06CmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gt06_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gt06CommonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gt06_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gt06_service_proto_goTypes,
		DependencyIndexes: file_gt06_service_proto_depIdxs,
		MessageInfos:      file_gt06_service_proto_msgTypes,
	}.Build()
	File_gt06_service_proto = out.File
	file_gt06_service_proto_rawDesc = nil
	file_gt06_service_proto_goTypes = nil
	file_gt06_service_proto_depIdxs = nil
}
