// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: device_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`                   //设备号
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`              //指令内容
	TimeId   uint64 `protobuf:"varint,4,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *SendCmdRequest) Reset() {
	*x = SendCmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmdRequest) ProtoMessage() {}

func (x *SendCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmdRequest.ProtoReflect.Descriptor instead.
func (*SendCmdRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendCmdRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SendCmdRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SendCmdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendCmdRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

type SendCmdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendCmdReply) Reset() {
	*x = SendCmdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmdReply) ProtoMessage() {}

func (x *SendCmdReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmdReply.ProtoReflect.Descriptor instead.
func (*SendCmdReply) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendCmdReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CommonReply) Reset() {
	*x = CommonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReply) ProtoMessage() {}

func (x *CommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReply.ProtoReflect.Descriptor instead.
func (*CommonReply) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{2}
}

func (x *CommonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OpenShortRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Seconds  int64  `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`             //录音时长，0表示持续录音
	TimeId   uint64 `protobuf:"varint,4,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *OpenShortRecordRequest) Reset() {
	*x = OpenShortRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenShortRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShortRecordRequest) ProtoMessage() {}

func (x *OpenShortRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShortRecordRequest.ProtoReflect.Descriptor instead.
func (*OpenShortRecordRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{3}
}

func (x *OpenShortRecordRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OpenShortRecordRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *OpenShortRecordRequest) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *OpenShortRecordRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

type VorRecordSwitchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Switch   int32  `protobuf:"varint,3,opt,name=switch,proto3" json:"switch,omitempty"`
	TimeId   uint64 `protobuf:"varint,4,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *VorRecordSwitchRequest) Reset() {
	*x = VorRecordSwitchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VorRecordSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VorRecordSwitchRequest) ProtoMessage() {}

func (x *VorRecordSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VorRecordSwitchRequest.ProtoReflect.Descriptor instead.
func (*VorRecordSwitchRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{4}
}

func (x *VorRecordSwitchRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *VorRecordSwitchRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *VorRecordSwitchRequest) GetSwitch() int32 {
	if x != nil {
		return x.Switch
	}
	return 0
}

func (x *VorRecordSwitchRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

type SetLocModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeId   uint64 `protobuf:"varint,3,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
	Mode     string `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Interval int32  `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"` //省电模式定位间隔
}

func (x *SetLocModeRequest) Reset() {
	*x = SetLocModeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocModeRequest) ProtoMessage() {}

func (x *SetLocModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocModeRequest.ProtoReflect.Descriptor instead.
func (*SetLocModeRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetLocModeRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SetLocModeRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SetLocModeRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

func (x *SetLocModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetLocModeRequest) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type LocateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeId   uint64 `protobuf:"varint,3,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *LocateRequest) Reset() {
	*x = LocateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateRequest) ProtoMessage() {}

func (x *LocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateRequest.ProtoReflect.Descriptor instead.
func (*LocateRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{6}
}

func (x *LocateRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *LocateRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *LocateRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

type SetShakeValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol   string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei       uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeId     uint64 `protobuf:"varint,3,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
	ShakeValue int32  `protobuf:"varint,4,opt,name=shake_value,json=shakeValue,proto3" json:"shake_value,omitempty"`
}

func (x *SetShakeValueRequest) Reset() {
	*x = SetShakeValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetShakeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetShakeValueRequest) ProtoMessage() {}

func (x *SetShakeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetShakeValueRequest.ProtoReflect.Descriptor instead.
func (*SetShakeValueRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetShakeValueRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SetShakeValueRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SetShakeValueRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

func (x *SetShakeValueRequest) GetShakeValue() int32 {
	if x != nil {
		return x.ShakeValue
	}
	return 0
}

type HandelDeviceCtrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeId   uint64 `protobuf:"varint,3,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
	Cmd      int32  `protobuf:"varint,4,opt,name=cmd,proto3" json:"cmd,omitempty"`                     //命令字
}

func (x *HandelDeviceCtrlRequest) Reset() {
	*x = HandelDeviceCtrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandelDeviceCtrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandelDeviceCtrlRequest) ProtoMessage() {}

func (x *HandelDeviceCtrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandelDeviceCtrlRequest.ProtoReflect.Descriptor instead.
func (*HandelDeviceCtrlRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{8}
}

func (x *HandelDeviceCtrlRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HandelDeviceCtrlRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *HandelDeviceCtrlRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

func (x *HandelDeviceCtrlRequest) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

type HandelRestartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`
	TimeId   uint64 `protobuf:"varint,3,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
}

func (x *HandelRestartRequest) Reset() {
	*x = HandelRestartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandelRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandelRestartRequest) ProtoMessage() {}

func (x *HandelRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandelRestartRequest.ProtoReflect.Descriptor instead.
func (*HandelRestartRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{9}
}

func (x *HandelRestartRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HandelRestartRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *HandelRestartRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

var File_device_service_proto protoreflect.FileDescriptor

var file_device_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x73, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65,
	0x69, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27,
	0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7b, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x6e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65,
	0x69, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x16, 0x56, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d,
	0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0x8c, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x58,
	0x0a, 0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x74,
	0x53, 0x68, 0x61, 0x6b, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65,
	0x69, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x74, 0x0a, 0x17, 0x48,
	0x61, 0x6e, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x74, 0x72, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x22, 0x5f, 0x0a, 0x14, 0x48, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65,
	0x49, 0x64, 0x32, 0xae, 0x04, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x12,
	0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x48, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x0f, 0x56, 0x6f, 0x72,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0d, 0x53,
	0x65, 0x74, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4a, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x74, 0x72, 0x6c, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x48, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x74, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a,
	0x0d, 0x48, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_device_service_proto_rawDescOnce sync.Once
	file_device_service_proto_rawDescData = file_device_service_proto_rawDesc
)

func file_device_service_proto_rawDescGZIP() []byte {
	file_device_service_proto_rawDescOnce.Do(func() {
		file_device_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_service_proto_rawDescData)
	})
	return file_device_service_proto_rawDescData
}

var file_device_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_device_service_proto_goTypes = []interface{}{
	(*SendCmdRequest)(nil),          // 0: service.SendCmdRequest
	(*SendCmdReply)(nil),            // 1: service.SendCmdReply
	(*CommonReply)(nil),             // 2: service.CommonReply
	(*OpenShortRecordRequest)(nil),  // 3: service.OpenShortRecordRequest
	(*VorRecordSwitchRequest)(nil),  // 4: service.VorRecordSwitchRequest
	(*SetLocModeRequest)(nil),       // 5: service.SetLocModeRequest
	(*LocateRequest)(nil),           // 6: service.LocateRequest
	(*SetShakeValueRequest)(nil),    // 7: service.SetShakeValueRequest
	(*HandelDeviceCtrlRequest)(nil), // 8: service.HandelDeviceCtrlRequest
	(*HandelRestartRequest)(nil),    // 9: service.HandelRestartRequest
}
var file_device_service_proto_depIdxs = []int32{
	0, // 0: service.DeviceService.SendCmd:input_type -> service.SendCmdRequest
	3, // 1: service.DeviceService.OpenShortRecord:input_type -> service.OpenShortRecordRequest
	4, // 2: service.DeviceService.VorRecordSwitch:input_type -> service.VorRecordSwitchRequest
	5, // 3: service.DeviceService.SetLocMode:input_type -> service.SetLocModeRequest
	6, // 4: service.DeviceService.Locate:input_type -> service.LocateRequest
	7, // 5: service.DeviceService.SetShakeValue:input_type -> service.SetShakeValueRequest
	8, // 6: service.DeviceService.HandelDeviceCtrl:input_type -> service.HandelDeviceCtrlRequest
	9, // 7: service.DeviceService.HandelRestart:input_type -> service.HandelRestartRequest
	1, // 8: service.DeviceService.SendCmd:output_type -> service.SendCmdReply
	2, // 9: service.DeviceService.OpenShortRecord:output_type -> service.CommonReply
	2, // 10: service.DeviceService.VorRecordSwitch:output_type -> service.CommonReply
	2, // 11: service.DeviceService.SetLocMode:output_type -> service.CommonReply
	2, // 12: service.DeviceService.Locate:output_type -> service.CommonReply
	2, // 13: service.DeviceService.SetShakeValue:output_type -> service.CommonReply
	2, // 14: service.DeviceService.HandelDeviceCtrl:output_type -> service.CommonReply
	2, // 15: service.DeviceService.HandelRestart:output_type -> service.CommonReply
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_service_proto_init() }
func file_device_service_proto_init() {
	if File_device_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenShortRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VorRecordSwitchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocModeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetShakeValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandelDeviceCtrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandelRestartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_service_proto_goTypes,
		DependencyIndexes: file_device_service_proto_depIdxs,
		MessageInfos:      file_device_service_proto_msgTypes,
	}.Build()
	File_device_service_proto = out.File
	file_device_service_proto_rawDesc = nil
	file_device_service_proto_goTypes = nil
	file_device_service_proto_depIdxs = nil
}
