// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: device_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imei    uint64 `protobuf:"varint,1,opt,name=imei,proto3" json:"imei,omitempty"`      //设备号
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` //指令内容
}

func (x *SendCmdRequest) Reset() {
	*x = SendCmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmdRequest) ProtoMessage() {}

func (x *SendCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmdRequest.ProtoReflect.Descriptor instead.
func (*SendCmdRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendCmdRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SendCmdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendCmdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendCmdReply) Reset() {
	*x = SendCmdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmdReply) ProtoMessage() {}

func (x *SendCmdReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmdReply.ProtoReflect.Descriptor instead.
func (*SendCmdReply) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendCmdReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CommonReply) Reset() {
	*x = CommonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReply) ProtoMessage() {}

func (x *CommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReply.ProtoReflect.Descriptor instead.
func (*CommonReply) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{2}
}

func (x *CommonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OpenShortRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imei    uint64 `protobuf:"varint,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Seconds uint64 `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"` //录音时长，0表示持续录音
}

func (x *OpenShortRecordRequest) Reset() {
	*x = OpenShortRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenShortRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShortRecordRequest) ProtoMessage() {}

func (x *OpenShortRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShortRecordRequest.ProtoReflect.Descriptor instead.
func (*OpenShortRecordRequest) Descriptor() ([]byte, []int) {
	return file_device_service_proto_rawDescGZIP(), []int{3}
}

func (x *OpenShortRecordRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *OpenShortRecordRequest) GetSeconds() uint64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

var File_device_service_proto protoreflect.FileDescriptor

var file_device_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x3e, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x28, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x46, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6d, 0x65, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x32, 0x94, 0x01, 0x0a, 0x0d, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x07,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_device_service_proto_rawDescOnce sync.Once
	file_device_service_proto_rawDescData = file_device_service_proto_rawDesc
)

func file_device_service_proto_rawDescGZIP() []byte {
	file_device_service_proto_rawDescOnce.Do(func() {
		file_device_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_service_proto_rawDescData)
	})
	return file_device_service_proto_rawDescData
}

var file_device_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_service_proto_goTypes = []interface{}{
	(*SendCmdRequest)(nil),         // 0: service.SendCmdRequest
	(*SendCmdReply)(nil),           // 1: service.SendCmdReply
	(*CommonReply)(nil),            // 2: service.CommonReply
	(*OpenShortRecordRequest)(nil), // 3: service.OpenShortRecordRequest
}
var file_device_service_proto_depIdxs = []int32{
	0, // 0: service.DeviceService.SendCmd:input_type -> service.SendCmdRequest
	3, // 1: service.DeviceService.OpenShortRecord:input_type -> service.OpenShortRecordRequest
	1, // 2: service.DeviceService.SendCmd:output_type -> service.SendCmdReply
	2, // 3: service.DeviceService.OpenShortRecord:output_type -> service.CommonReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_service_proto_init() }
func file_device_service_proto_init() {
	if File_device_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenShortRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_service_proto_goTypes,
		DependencyIndexes: file_device_service_proto_depIdxs,
		MessageInfos:      file_device_service_proto_msgTypes,
	}.Build()
	File_device_service_proto = out.File
	file_device_service_proto_rawDesc = nil
	file_device_service_proto_goTypes = nil
	file_device_service_proto_depIdxs = nil
}
