// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: hl3g_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendHl3GCmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Imei     uint64 `protobuf:"varint,2,opt,name=imei,proto3" json:"imei,omitempty"`                   //设备号
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`              //指令内容
	TimeId   uint64 `protobuf:"varint,4,opt,name=time_id,json=timeId,proto3" json:"time_id,omitempty"` //cmd的key
	Proto    string `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty"`                  //指令类型
}

func (x *SendHl3GCmdRequest) Reset() {
	*x = SendHl3GCmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hl3g_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHl3GCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHl3GCmdRequest) ProtoMessage() {}

func (x *SendHl3GCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hl3g_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHl3GCmdRequest.ProtoReflect.Descriptor instead.
func (*SendHl3GCmdRequest) Descriptor() ([]byte, []int) {
	return file_hl3g_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendHl3GCmdRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SendHl3GCmdRequest) GetImei() uint64 {
	if x != nil {
		return x.Imei
	}
	return 0
}

func (x *SendHl3GCmdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendHl3GCmdRequest) GetTimeId() uint64 {
	if x != nil {
		return x.TimeId
	}
	return 0
}

func (x *SendHl3GCmdRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

type Hl3GCommonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Hl3GCommonReply) Reset() {
	*x = Hl3GCommonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hl3g_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hl3GCommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hl3GCommonReply) ProtoMessage() {}

func (x *Hl3GCommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_hl3g_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hl3GCommonReply.ProtoReflect.Descriptor instead.
func (*Hl3GCommonReply) Descriptor() ([]byte, []int) {
	return file_hl3g_service_proto_rawDescGZIP(), []int{1}
}

func (x *Hl3GCommonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hl3g_service_proto protoreflect.FileDescriptor

var file_hl3g_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x6c, 0x33, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x8d, 0x01,
	0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x6c, 0x33, 0x67, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x69, 0x6d, 0x65, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a,
	0x0f, 0x48, 0x6c, 0x33, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4f, 0x0a, 0x0b, 0x48, 0x6c,
	0x33, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x6d, 0x64, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x48, 0x6c, 0x33, 0x67, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x6c, 0x33, 0x67,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hl3g_service_proto_rawDescOnce sync.Once
	file_hl3g_service_proto_rawDescData = file_hl3g_service_proto_rawDesc
)

func file_hl3g_service_proto_rawDescGZIP() []byte {
	file_hl3g_service_proto_rawDescOnce.Do(func() {
		file_hl3g_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hl3g_service_proto_rawDescData)
	})
	return file_hl3g_service_proto_rawDescData
}

var file_hl3g_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hl3g_service_proto_goTypes = []interface{}{
	(*SendHl3GCmdRequest)(nil), // 0: service.SendHl3gCmdRequest
	(*Hl3GCommonReply)(nil),    // 1: service.Hl3gCommonReply
}
var file_hl3g_service_proto_depIdxs = []int32{
	0, // 0: service.Hl3gService.SendCmd:input_type -> service.SendHl3gCmdRequest
	1, // 1: service.Hl3gService.SendCmd:output_type -> service.Hl3gCommonReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hl3g_service_proto_init() }
func file_hl3g_service_proto_init() {
	if File_hl3g_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hl3g_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendHl3GCmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hl3g_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hl3GCommonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hl3g_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hl3g_service_proto_goTypes,
		DependencyIndexes: file_hl3g_service_proto_depIdxs,
		MessageInfos:      file_hl3g_service_proto_msgTypes,
	}.Build()
	File_hl3g_service_proto = out.File
	file_hl3g_service_proto_rawDesc = nil
	file_hl3g_service_proto_goTypes = nil
	file_hl3g_service_proto_depIdxs = nil
}
