// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: hl3g_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Hl3GServiceClient is the client API for Hl3GService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Hl3GServiceClient interface {
	SendCmd(ctx context.Context, in *SendHl3GCmdRequest, opts ...grpc.CallOption) (*Hl3GCommonReply, error)
}

type hl3GServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHl3GServiceClient(cc grpc.ClientConnInterface) Hl3GServiceClient {
	return &hl3GServiceClient{cc}
}

func (c *hl3GServiceClient) SendCmd(ctx context.Context, in *SendHl3GCmdRequest, opts ...grpc.CallOption) (*Hl3GCommonReply, error) {
	out := new(Hl3GCommonReply)
	err := c.cc.Invoke(ctx, "/service.Hl3gService/SendCmd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Hl3GServiceServer is the server API for Hl3GService service.
// All implementations must embed UnimplementedHl3GServiceServer
// for forward compatibility
type Hl3GServiceServer interface {
	SendCmd(context.Context, *SendHl3GCmdRequest) (*Hl3GCommonReply, error)
	mustEmbedUnimplementedHl3GServiceServer()
}

// UnimplementedHl3GServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHl3GServiceServer struct {
}

func (UnimplementedHl3GServiceServer) SendCmd(context.Context, *SendHl3GCmdRequest) (*Hl3GCommonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCmd not implemented")
}
func (UnimplementedHl3GServiceServer) mustEmbedUnimplementedHl3GServiceServer() {}

// UnsafeHl3GServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Hl3GServiceServer will
// result in compilation errors.
type UnsafeHl3GServiceServer interface {
	mustEmbedUnimplementedHl3GServiceServer()
}

func RegisterHl3GServiceServer(s grpc.ServiceRegistrar, srv Hl3GServiceServer) {
	s.RegisterService(&Hl3GService_ServiceDesc, srv)
}

func _Hl3GService_SendCmd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendHl3GCmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hl3GServiceServer).SendCmd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Hl3gService/SendCmd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hl3GServiceServer).SendCmd(ctx, req.(*SendHl3GCmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hl3GService_ServiceDesc is the grpc.ServiceDesc for Hl3GService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hl3GService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Hl3gService",
	HandlerType: (*Hl3GServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCmd",
			Handler:    _Hl3GService_SendCmd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hl3g_service.proto",
}
